### ISSUE TITLE
Get this working again

### ISSUE THREAD

**Issue by iamgreaser** [FabricMC/fabric-mod-template#1]
Depends on fabric-loom which is missing from the maven server.

While someone unbreaks the maven server, could we get some instructions on how to build this without the maven server?

**Comment by modmuss50** [comment]
Build a copy of loom or find it on the jenkins(if its on there). 
Create a folder called libs in the root of the project called `libs`
then add this in the build script repo section of `build.gradle`
`repositories {
        flatDir dirs: "libs"
    }`

**Comment by modmuss50** [comment]
loom is now on maven, but fabric base isnt just yet.
